#!/usr/bin/env python3
# encoding: utf-8

"""
Comprehensive tests for the RMGConstantTP simulate adapter and the
standalone RMG SA CSV parser.

The RMG subprocess (run_rmg_sa_incore) requires the rmg_env conda
environment.  Tests that exercise the full subprocess pipeline are
marked with ``@pytest.mark.rmg_env`` and skipped when rmg_env is not
available.  All other tests use synthetic CSV/YAML fixtures and mocked
subprocesses.
"""

import os
import shutil
from unittest import mock

import numpy as np
import yaml

from t3.common import (SIMULATE_TEST_DATA_BASE_PATH, get_chem_to_rmg_rxn_index_map,
                        sa_dict_to_yaml, sa_dict_from_yaml, save_yaml_file)
from tests.common import run_minimal
from t3.simulate.adapter import SimulateAdapter
from t3.simulate.rmg_constant_tp import RMGConstantTP
from t3.simulate.factory import _registered_simulate_adapters, simulate_factory
from t3.utils.rmg_sa_parser import (parse_rmg_sa_csv, parse_rmg_sa_csvs,
                                     rmg_sa_csvs_to_sa_dict, _strip_rmg_index)


TEST_DIR = os.path.join(SIMULATE_TEST_DATA_BASE_PATH, 'rmg_simulator_test')
CHEM_ANNOTATED = os.path.join(TEST_DIR, 'iteration_0', 'RMG', 'chemkin', 'chem_annotated.inp')
SA_SOLVER_DIR = os.path.join(TEST_DIR, 'iteration_0', 'SA', 'solver')
SA_DIR = os.path.join(TEST_DIR, 'iteration_0', 'SA')

# Files generated by tests that should be cleaned up (not the fixture CSVs)
_GENERATED_FILES = []


def _make_adapter(observable_list=None):
    """Helper to construct an RMGConstantTP adapter using the minimal example."""
    t3 = run_minimal(project_directory=TEST_DIR)
    t3.set_paths()
    adapter = RMGConstantTP(t3=t3.t3,
                             rmg=t3.rmg,
                             paths=t3.paths,
                             logger=t3.logger,
                             atol=t3.rmg['model']['atol'],
                             rtol=t3.rmg['model']['rtol'],
                             observable_list=observable_list or list(),
                             sa_atol=t3.t3['sensitivity']['atol'],
                             sa_rtol=t3.t3['sensitivity']['rtol'],
                             )
    return adapter


def _mock_simulate(adapter):
    """Simulate what run_rmg_sa_incore does: parse CSV fixtures and write sa_output.yml."""
    raw = parse_rmg_sa_csvs(os.path.join(adapter.paths['SA'], 'solver'))
    with open(adapter.sa_output_file, 'w') as f:
        yaml.dump(raw, f, default_flow_style=False)
    _GENERATED_FILES.append(adapter.sa_output_file)


# ===========================================================================
# CSV Parser — _strip_rmg_index
# ===========================================================================

def test_strip_rmg_index_with_id():
    assert _strip_rmg_index('OH(4)') == 'OH'


def test_strip_rmg_index_nested_parens():
    assert _strip_rmg_index('O(T)(5)') == 'O(T)'


def test_strip_rmg_index_no_id():
    assert _strip_rmg_index('H2O') == 'H2O'


def test_strip_rmg_index_empty():
    assert _strip_rmg_index('') == ''


# ===========================================================================
# CSV Parser — parse_rmg_sa_csv (single file)
# ===========================================================================

def test_parse_single_csv_returns_time():
    csv_path = os.path.join(SA_SOLVER_DIR, 'sensitivity_1_SPC_3.csv')
    time_data, _, _ = parse_rmg_sa_csv(csv_path)
    assert len(time_data) == 10
    assert time_data[0] == 0.0
    assert time_data[-1] == 5.0


def test_parse_single_csv_time_monotonic():
    csv_path = os.path.join(SA_SOLVER_DIR, 'sensitivity_1_SPC_3.csv')
    time_data, _, _ = parse_rmg_sa_csv(csv_path)
    assert all(time_data[i] < time_data[i + 1] for i in range(len(time_data) - 1))


def test_parse_single_csv_kinetics_structure():
    """Each CSV file has one observable; kinetics should have one key."""
    csv_path = os.path.join(SA_SOLVER_DIR, 'sensitivity_1_SPC_3.csv')
    _, kinetics, _ = parse_rmg_sa_csv(csv_path)
    assert 'H' in kinetics
    assert len(kinetics) == 1  # only one observable per CSV
    assert len(kinetics['H']) == 18  # 18 reactions


def test_parse_single_csv_kinetics_keys_are_ints():
    csv_path = os.path.join(SA_SOLVER_DIR, 'sensitivity_1_SPC_3.csv')
    _, kinetics, _ = parse_rmg_sa_csv(csv_path)
    for rxn_key in kinetics['H']:
        assert isinstance(rxn_key, int)
        assert 1 <= rxn_key <= 18


def test_parse_single_csv_kinetics_values_length():
    csv_path = os.path.join(SA_SOLVER_DIR, 'sensitivity_1_SPC_3.csv')
    time_data, kinetics, _ = parse_rmg_sa_csv(csv_path)
    for rxn_key, values in kinetics['H'].items():
        assert len(values) == len(time_data)


def test_parse_single_csv_thermo_structure():
    csv_path = os.path.join(SA_SOLVER_DIR, 'sensitivity_1_SPC_3.csv')
    _, _, thermo = parse_rmg_sa_csv(csv_path)
    assert 'H' in thermo
    assert len(thermo) == 1
    # 8 species: H2, O2, H, OH, O(T), HO2, H2O, OO (inerts excluded from SA headers)
    assert len(thermo['H']) == 8


def test_parse_single_csv_thermo_labels_strip_id():
    """Thermo SA labels should have RMG index stripped."""
    csv_path = os.path.join(SA_SOLVER_DIR, 'sensitivity_1_SPC_3.csv')
    _, _, thermo = parse_rmg_sa_csv(csv_path)
    expected_labels = {'H2', 'O2', 'H', 'OH', 'O(T)', 'HO2', 'H2O', 'OO'}
    assert set(thermo['H'].keys()) == expected_labels


def test_parse_single_csv_observable_label_strips_id():
    """Observable label 'H(3)' in the header should become 'H'."""
    csv_path = os.path.join(SA_SOLVER_DIR, 'sensitivity_1_SPC_3.csv')
    _, kinetics, thermo = parse_rmg_sa_csv(csv_path)
    assert 'H' in kinetics
    assert 'H(3)' not in kinetics
    assert 'H' in thermo


def test_parse_single_csv_oh_observable():
    csv_path = os.path.join(SA_SOLVER_DIR, 'sensitivity_1_SPC_4.csv')
    _, kinetics, thermo = parse_rmg_sa_csv(csv_path)
    assert 'OH' in kinetics
    assert 'OH' in thermo
    assert len(kinetics['OH']) == 18
    assert len(thermo['OH']) == 8


def test_parse_single_csv_nonzero_kinetics():
    """At least some kinetics SA coefficients should be non-zero."""
    csv_path = os.path.join(SA_SOLVER_DIR, 'sensitivity_1_SPC_3.csv')
    _, kinetics, _ = parse_rmg_sa_csv(csv_path)
    max_abs = max(max(abs(v) for v in values) for values in kinetics['H'].values())
    assert max_abs > 0.01, 'All kinetics SA coefficients are near zero'


def test_parse_single_csv_nonzero_thermo():
    """At least some thermo SA coefficients should be non-zero."""
    csv_path = os.path.join(SA_SOLVER_DIR, 'sensitivity_1_SPC_3.csv')
    _, _, thermo = parse_rmg_sa_csv(csv_path)
    max_abs = max(max(abs(v) for v in values) for values in thermo['H'].values())
    assert max_abs > 0.001, 'All thermo SA coefficients are near zero'


def test_parse_single_csv_initial_values_zero():
    """At t=0, all SA coefficients should be zero."""
    csv_path = os.path.join(SA_SOLVER_DIR, 'sensitivity_1_SPC_3.csv')
    _, kinetics, thermo = parse_rmg_sa_csv(csv_path)
    for values in kinetics['H'].values():
        assert values[0] == 0.0
    for values in thermo['H'].values():
        assert values[0] == 0.0


# ===========================================================================
# CSV Parser — parse_rmg_sa_csvs (all files in solver dir)
# ===========================================================================

def test_parse_all_csvs_merges_observables():
    raw = parse_rmg_sa_csvs(SA_SOLVER_DIR)
    assert 'H' in raw['kinetics']
    assert 'OH' in raw['kinetics']
    assert 'H' in raw['thermo']
    assert 'OH' in raw['thermo']


def test_parse_all_csvs_time_from_first_file():
    raw = parse_rmg_sa_csvs(SA_SOLVER_DIR)
    assert len(raw['time']) == 10
    assert raw['time'][0] == 0.0


def test_parse_all_csvs_kinetics_count():
    raw = parse_rmg_sa_csvs(SA_SOLVER_DIR)
    assert len(raw['kinetics']) == 2  # H and OH
    for obs in ['H', 'OH']:
        assert len(raw['kinetics'][obs]) == 18


def test_parse_all_csvs_thermo_count():
    raw = parse_rmg_sa_csvs(SA_SOLVER_DIR)
    assert len(raw['thermo']) == 2
    for obs in ['H', 'OH']:
        assert len(raw['thermo'][obs]) == 8


def test_parse_all_csvs_empty_directory(tmp_path):
    raw = parse_rmg_sa_csvs(str(tmp_path))
    assert raw == {'time': [], 'kinetics': {}, 'thermo': {}}


def test_parse_all_csvs_nonexistent_directory():
    raw = parse_rmg_sa_csvs('/nonexistent/path')
    assert raw == {'time': [], 'kinetics': {}, 'thermo': {}}


# ===========================================================================
# CSV Parser — rmg_sa_csvs_to_sa_dict (full conversion)
# ===========================================================================

def test_sa_dict_format_per_condition():
    """rmg_sa_csvs_to_sa_dict returns per-condition list format."""
    sa_dict = rmg_sa_csvs_to_sa_dict(SA_SOLVER_DIR)
    assert isinstance(sa_dict['time'], list)
    assert isinstance(sa_dict['kinetics'], list)
    assert isinstance(sa_dict['thermo'], list)
    assert len(sa_dict['time']) == 1
    assert len(sa_dict['kinetics']) == 1
    assert len(sa_dict['thermo']) == 1


def test_sa_dict_time_is_numpy():
    sa_dict = rmg_sa_csvs_to_sa_dict(SA_SOLVER_DIR)
    assert isinstance(sa_dict['time'][0], np.ndarray)
    assert len(sa_dict['time'][0]) == 10


def test_sa_dict_kinetics_values_are_numpy():
    sa_dict = rmg_sa_csvs_to_sa_dict(SA_SOLVER_DIR)
    for obs, params in sa_dict['kinetics'][0].items():
        for rxn_key, values in params.items():
            assert isinstance(values, np.ndarray), \
                f'kinetics/{obs}/{rxn_key} is {type(values)}, expected np.ndarray'


def test_sa_dict_thermo_values_are_numpy():
    sa_dict = rmg_sa_csvs_to_sa_dict(SA_SOLVER_DIR)
    for obs, params in sa_dict['thermo'][0].items():
        for spc_key, values in params.items():
            assert isinstance(values, np.ndarray), \
                f'thermo/{obs}/{spc_key} is {type(values)}, expected np.ndarray'


def test_sa_dict_without_index_mapping():
    """Without chem_annotated_path, keys are raw RMG indices (1-based ints)."""
    sa_dict = rmg_sa_csvs_to_sa_dict(SA_SOLVER_DIR, chem_annotated_path=None)
    for obs, params in sa_dict['kinetics'][0].items():
        for rxn_key in params:
            assert isinstance(rxn_key, int)
            assert 1 <= rxn_key <= 18


def test_sa_dict_with_index_mapping():
    """With chem_annotated_path, RMG indices are mapped to Chemkin indices."""
    sa_dict = rmg_sa_csvs_to_sa_dict(SA_SOLVER_DIR, chem_annotated_path=CHEM_ANNOTATED)
    # Check that the keys reflect Chemkin indices (which may differ from RMG indices)
    for obs, params in sa_dict['kinetics'][0].items():
        for rxn_key in params:
            assert isinstance(rxn_key, int)


def test_sa_dict_index_mapping_has_duplicates():
    """The minimal model has duplicate reactions (Chemkin #12 and #18 both map to RMG #2 and #23).
    Verify the Chemkin→RMG map is non-trivial."""
    chem_to_rmg = get_chem_to_rmg_rxn_index_map(CHEM_ANNOTATED)
    # Chemkin #12 maps to RMG #2, Chemkin #18 maps to RMG #23 — both are O(T)+H=OH duplicates
    assert 12 in chem_to_rmg
    assert 18 in chem_to_rmg
    assert chem_to_rmg[12] == 2  # RMG #2
    assert chem_to_rmg[18] == 23  # RMG #23


def test_sa_dict_kinetics_specific_values():
    """Check specific SA values from the CSV fixture."""
    sa_dict = rmg_sa_csvs_to_sa_dict(SA_SOLVER_DIR)
    h_kinetics = sa_dict['kinetics'][0]['H']
    # Reaction k2 at t=0.01 should be 0.418 (3rd row, 2nd SA column)
    np.testing.assert_allclose(h_kinetics[2][2], 0.418, atol=1e-6)
    # Reaction k3 at t=0.1 should be -0.478 (4th row)
    np.testing.assert_allclose(h_kinetics[3][3], -0.478, atol=1e-6)


def test_sa_dict_thermo_specific_values():
    """Check specific thermo SA values from the CSV fixture."""
    sa_dict = rmg_sa_csvs_to_sa_dict(SA_SOLVER_DIR)
    h_thermo = sa_dict['thermo'][0]['H']
    # dG[H2] at t=0.001 should be 0.015 (2nd row)
    np.testing.assert_allclose(h_thermo['H2'][1], 0.015, atol=1e-6)


# ===========================================================================
# Adapter — Registration and Inheritance
# ===========================================================================

def test_adapter_registered_in_factory():
    assert 'RMGConstantTP' in _registered_simulate_adapters
    assert _registered_simulate_adapters['RMGConstantTP'] is RMGConstantTP


def test_adapter_is_simulate_adapter():
    assert issubclass(RMGConstantTP, SimulateAdapter)


def test_adapter_via_factory():
    t3 = run_minimal(project_directory=TEST_DIR)
    t3.set_paths()
    adapter = simulate_factory(simulate_method='RMGConstantTP',
                                t3=t3.t3,
                                rmg=t3.rmg,
                                paths=t3.paths,
                                logger=t3.logger,
                                atol=t3.rmg['model']['atol'],
                                rtol=t3.rmg['model']['rtol'],
                                observable_list=['OH'],
                                )
    assert isinstance(adapter, RMGConstantTP)


# ===========================================================================
# Adapter — Initialization and set_up
# ===========================================================================

def test_adapter_init_no_sa():
    adapter = _make_adapter(observable_list=[])
    assert adapter.rmg_input_file is not None
    assert adapter.sa_output_file is None
    assert adapter.observable_list == []


def test_adapter_init_with_sa():
    adapter = _make_adapter(observable_list=['OH', 'H'])
    assert adapter.rmg_input_file is not None
    assert adapter.sa_output_file is not None
    assert adapter.observable_list == ['OH', 'H']


def test_set_up_creates_sa_directory():
    adapter = _make_adapter(observable_list=['OH'])
    assert os.path.isdir(adapter.paths['SA'])


def test_set_up_writes_rmg_input_file():
    adapter = _make_adapter(observable_list=['OH'])
    assert os.path.isfile(adapter.rmg_input_file)
    _GENERATED_FILES.append(adapter.rmg_input_file)


def test_set_up_no_sa_uses_rmg_input():
    adapter = _make_adapter(observable_list=[])
    assert adapter.rmg_input_file == adapter.paths['RMG input']


def test_set_up_sa_uses_sa_input():
    adapter = _make_adapter(observable_list=['OH'])
    assert adapter.rmg_input_file == adapter.paths['SA input']


# ===========================================================================
# Adapter — simulate with mocked subprocess
# ===========================================================================

def test_simulate_calls_run_rmg_sa_incore():
    """Verify simulate() calls run_rmg_sa_incore when observables are present."""
    adapter = _make_adapter(observable_list=['OH', 'H'])
    with mock.patch('t3.simulate.rmg_constant_tp.run_rmg_sa_incore',
                    return_value=(True, None)) as mock_run:
        adapter.simulate()
    mock_run.assert_called_once()


def test_simulate_no_sa_skips_subprocess():
    """Without observables, simulate() should NOT call run_rmg_sa_incore."""
    adapter = _make_adapter(observable_list=[])
    with mock.patch('t3.simulate.rmg_constant_tp.run_rmg_sa_incore') as mock_run:
        adapter.simulate()
    mock_run.assert_not_called()


def test_simulate_passes_correct_args():
    """Verify simulate() passes the correct arguments to run_rmg_sa_incore."""
    adapter = _make_adapter(observable_list=['OH', 'H'])
    with mock.patch('t3.simulate.rmg_constant_tp.run_rmg_sa_incore',
                    return_value=(True, None)) as mock_run:
        adapter.simulate()
    call_kwargs = mock_run.call_args
    assert call_kwargs.kwargs['rmg_input_file_path'] == adapter.rmg_input_file
    assert call_kwargs.kwargs['chemkin_file_path'] == adapter.paths['chem annotated']
    assert call_kwargs.kwargs['species_dict_path'] == adapter.paths['species dict']
    assert call_kwargs.kwargs['output_path'] == adapter.sa_output_file
    assert call_kwargs.kwargs['observables'] == ['OH', 'H']


# ===========================================================================
# Adapter — get_sa_coefficients with mock YAML
# ===========================================================================

def test_get_sa_coefficients_structure():
    """Verify sa_dict has correct per-condition list structure."""
    adapter = _make_adapter(observable_list=['OH', 'H'])
    _mock_simulate(adapter)
    sa_dict = adapter.get_sa_coefficients()
    assert sa_dict is not None
    assert isinstance(sa_dict['time'], list)
    assert isinstance(sa_dict['kinetics'], list)
    assert isinstance(sa_dict['thermo'], list)
    assert len(sa_dict['time']) == 1
    assert len(sa_dict['kinetics']) == 1
    assert len(sa_dict['thermo']) == 1


def test_get_sa_coefficients_time():
    adapter = _make_adapter(observable_list=['OH', 'H'])
    _mock_simulate(adapter)
    sa_dict = adapter.get_sa_coefficients()
    assert isinstance(sa_dict['time'][0], np.ndarray)
    assert len(sa_dict['time'][0]) == 10
    assert sa_dict['time'][0][0] == 0.0
    assert sa_dict['time'][0][-1] == 5.0


def test_get_sa_coefficients_kinetics_observables():
    adapter = _make_adapter(observable_list=['OH', 'H'])
    _mock_simulate(adapter)
    sa_dict = adapter.get_sa_coefficients()
    assert len(sa_dict['kinetics'][0]) == 2
    assert 'H' in sa_dict['kinetics'][0]
    assert 'OH' in sa_dict['kinetics'][0]


def test_get_sa_coefficients_thermo_observables():
    adapter = _make_adapter(observable_list=['OH', 'H'])
    _mock_simulate(adapter)
    sa_dict = adapter.get_sa_coefficients()
    assert len(sa_dict['thermo'][0]) == 2
    assert 'H' in sa_dict['thermo'][0]
    assert 'OH' in sa_dict['thermo'][0]


def test_get_sa_coefficients_kinetics_values_are_numpy():
    adapter = _make_adapter(observable_list=['OH', 'H'])
    _mock_simulate(adapter)
    sa_dict = adapter.get_sa_coefficients()
    for obs, params in sa_dict['kinetics'][0].items():
        for rxn_key, values in params.items():
            assert isinstance(values, np.ndarray)
            assert len(values) == 10


def test_get_sa_coefficients_thermo_values_are_numpy():
    adapter = _make_adapter(observable_list=['OH', 'H'])
    _mock_simulate(adapter)
    sa_dict = adapter.get_sa_coefficients()
    for obs, params in sa_dict['thermo'][0].items():
        for spc_key, values in params.items():
            assert isinstance(values, np.ndarray)
            assert len(values) == 10


def test_get_sa_coefficients_thermo_keys_are_species():
    adapter = _make_adapter(observable_list=['OH', 'H'])
    _mock_simulate(adapter)
    sa_dict = adapter.get_sa_coefficients()
    for obs, params in sa_dict['thermo'][0].items():
        for spc_key in params:
            assert isinstance(spc_key, str)
            assert len(spc_key) > 0


def test_get_sa_coefficients_kinetics_reaction_count():
    adapter = _make_adapter(observable_list=['OH', 'H'])
    _mock_simulate(adapter)
    sa_dict = adapter.get_sa_coefficients()
    for obs, params in sa_dict['kinetics'][0].items():
        # Index mapping may remap some reaction indices; verify we have entries
        assert len(params) >= 10, \
            f'{obs} has only {len(params)} kinetics entries, expected >= 10'


def test_get_sa_coefficients_index_mapping():
    """Verify get_sa_coefficients maps RMG indices to Chemkin indices."""
    adapter = _make_adapter(observable_list=['OH', 'H'])
    _mock_simulate(adapter)
    sa_dict = adapter.get_sa_coefficients()
    # All kinetics keys should be Chemkin indices (ints)
    for obs, params in sa_dict['kinetics'][0].items():
        for rxn_key in params:
            assert isinstance(rxn_key, int)


def test_get_sa_coefficients_missing_file():
    adapter = _make_adapter(observable_list=['OH', 'H'])
    # Don't create sa_output.yml
    sa_dict = adapter.get_sa_coefficients()
    assert sa_dict is None


def test_get_sa_coefficients_nonzero_kinetics():
    adapter = _make_adapter(observable_list=['OH', 'H'])
    _mock_simulate(adapter)
    sa_dict = adapter.get_sa_coefficients()
    max_abs = 0.0
    for obs, params in sa_dict['kinetics'][0].items():
        for rxn_key, values in params.items():
            max_abs = max(max_abs, np.max(np.abs(values)))
    assert max_abs > 0.01


def test_get_sa_coefficients_nonzero_thermo():
    adapter = _make_adapter(observable_list=['OH', 'H'])
    _mock_simulate(adapter)
    sa_dict = adapter.get_sa_coefficients()
    max_abs = 0.0
    for obs, params in sa_dict['thermo'][0].items():
        for spc_key, values in params.items():
            max_abs = max(max_abs, np.max(np.abs(values)))
    assert max_abs > 0.001


# ===========================================================================
# Adapter — get_idt_by_T
# ===========================================================================

def test_get_idt_returns_empty():
    """Constant T,P reactor has no ignition."""
    adapter = _make_adapter(observable_list=[])
    idt_dict = adapter.get_idt_by_T()
    assert idt_dict == {'idt': [], 'idt_index': []}


# ===========================================================================
# Adapter — generate_rmg_reactors_for_simulation
# ===========================================================================

def test_generate_reactors_no_ranges():
    """Without ranged parameters, returns rmg dict unchanged."""
    adapter = _make_adapter(observable_list=[])
    result = adapter.generate_rmg_reactors_for_simulation()
    assert result is adapter.rmg  # identity, not a copy


def test_generate_reactors_with_ranged_temperature_and_pressure():
    """Ranged T and P should expand into individual reactors."""
    adapter = _make_adapter(observable_list=[])
    # Modify the first reactor to have ranged T and P
    original_t = adapter.rmg['reactors'][0]['T']
    original_p = adapter.rmg['reactors'][0]['P']
    adapter.rmg['reactors'][0]['T'] = [800, 1200]
    adapter.rmg['reactors'][0]['P'] = [1, 10]
    result = adapter.generate_rmg_reactors_for_simulation()
    # Should have expanded into multiple reactors (T x P grid)
    assert len(result['reactors']) >= 4
    for reactor in result['reactors']:
        assert isinstance(reactor['T'], (int, float))
        assert 800 <= reactor['T'] <= 1200
        assert isinstance(reactor['P'], (int, float))
        assert 1 <= reactor['P'] <= 10
    # Restore
    adapter.rmg['reactors'][0]['T'] = original_t
    adapter.rmg['reactors'][0]['P'] = original_p


# ===========================================================================
# YAML Serialization Round-trip
# ===========================================================================

def test_sa_dict_yaml_round_trip(tmp_path):
    """Serialize sa_dict to YAML and deserialize; verify round-trip fidelity."""
    adapter = _make_adapter(observable_list=['OH', 'H'])
    _mock_simulate(adapter)
    sa_dict = adapter.get_sa_coefficients()

    metadata = {'adapter': 'RMGConstantTP', 'iteration': 0,
                'observables': list(sa_dict['kinetics'][0].keys())}
    serialized = sa_dict_to_yaml(sa_dict, metadata=metadata)

    # Verify conditions structure
    assert 'conditions' in serialized
    assert len(serialized['conditions']) == 1

    sa_path = str(tmp_path / 'sa_coefficients.yml')
    save_yaml_file(path=sa_path, content=serialized, top_keys=['metadata'])

    from arc.common import read_yaml_file
    loaded_raw = read_yaml_file(path=sa_path)
    loaded = sa_dict_from_yaml(loaded_raw)

    # Time
    np.testing.assert_array_almost_equal(loaded['time'][0], sa_dict['time'][0])

    # Kinetics
    assert set(loaded['kinetics'][0].keys()) == set(sa_dict['kinetics'][0].keys())
    for obs in sa_dict['kinetics'][0]:
        for param in sa_dict['kinetics'][0][obs]:
            np.testing.assert_array_almost_equal(
                loaded['kinetics'][0][obs][param],
                sa_dict['kinetics'][0][obs][param])

    # Thermo
    assert set(loaded['thermo'][0].keys()) == set(sa_dict['thermo'][0].keys())
    for obs in sa_dict['thermo'][0]:
        for param in sa_dict['thermo'][0][obs]:
            np.testing.assert_array_almost_equal(
                loaded['thermo'][0][obs][param],
                sa_dict['thermo'][0][obs][param])


def test_sa_dict_yaml_metadata(tmp_path):
    """Metadata should be preserved in YAML round-trip."""
    adapter = _make_adapter(observable_list=['OH', 'H'])
    _mock_simulate(adapter)
    sa_dict = adapter.get_sa_coefficients()

    metadata = {'adapter': 'RMGConstantTP', 'iteration': 0,
                'observables': sorted(sa_dict['kinetics'][0].keys())}
    serialized = sa_dict_to_yaml(sa_dict, metadata=metadata)

    sa_path = str(tmp_path / 'sa_coefficients.yml')
    save_yaml_file(path=sa_path, content=serialized, top_keys=['metadata'])

    from arc.common import read_yaml_file
    loaded = read_yaml_file(path=sa_path)
    assert loaded['metadata']['adapter'] == 'RMGConstantTP'
    assert loaded['metadata']['iteration'] == 0
    assert set(loaded['metadata']['observables']) == {'H', 'OH'}


# ===========================================================================
# CSV-to-sa_dict matches adapter's YAML-based get_sa_coefficients
# ===========================================================================

def test_csv_parser_matches_adapter():
    """The standalone CSV parser should produce the same sa_dict as the adapter."""
    adapter = _make_adapter(observable_list=['OH', 'H'])
    _mock_simulate(adapter)
    sa_dict_yaml = adapter.get_sa_coefficients()

    sa_dict_csv = rmg_sa_csvs_to_sa_dict(
        os.path.join(adapter.paths['SA'], 'solver'),
        chem_annotated_path=adapter.paths['chem annotated'],
    )

    # Time should match
    np.testing.assert_array_almost_equal(sa_dict_csv['time'][0], sa_dict_yaml['time'][0])

    # Observables should match
    assert set(sa_dict_csv['kinetics'][0].keys()) == set(sa_dict_yaml['kinetics'][0].keys())
    assert set(sa_dict_csv['thermo'][0].keys()) == set(sa_dict_yaml['thermo'][0].keys())

    # Kinetics values should match
    for obs in sa_dict_yaml['kinetics'][0]:
        yaml_params = sa_dict_yaml['kinetics'][0][obs]
        csv_params = sa_dict_csv['kinetics'][0][obs]
        assert set(csv_params.keys()) == set(yaml_params.keys()), \
            f'Kinetics key mismatch for {obs}: csv={set(csv_params.keys())} yaml={set(yaml_params.keys())}'
        for param in yaml_params:
            np.testing.assert_array_almost_equal(
                csv_params[param], yaml_params[param],
                err_msg=f'kinetics/{obs}/{param} mismatch')

    # Thermo values should match
    for obs in sa_dict_yaml['thermo'][0]:
        yaml_params = sa_dict_yaml['thermo'][0][obs]
        csv_params = sa_dict_csv['thermo'][0][obs]
        assert set(csv_params.keys()) == set(yaml_params.keys())
        for param in yaml_params:
            np.testing.assert_array_almost_equal(
                csv_params[param], yaml_params[param],
                err_msg=f'thermo/{obs}/{param} mismatch')


# ===========================================================================
# Teardown
# ===========================================================================

def teardown_module():
    """Clean up generated files without destroying CSV/YAML test fixtures."""
    # Clean up files generated by tests
    for f in _GENERATED_FILES:
        if os.path.isfile(f):
            os.remove(f)
    # Clean up log files and generated directories
    for f in [os.path.join(TEST_DIR, 't3.log')]:
        if os.path.isfile(f):
            os.remove(f)
    log_archive = os.path.join(TEST_DIR, 'log_archive')
    if os.path.isdir(log_archive):
        shutil.rmtree(log_archive, ignore_errors=True)
    # Clean up generated input.py files (not the fixture data)
    sa_input = os.path.join(SA_DIR, 'input.py')
    if os.path.isfile(sa_input):
        os.remove(sa_input)
    sa_output = os.path.join(SA_DIR, 'sa_output.yml')
    if os.path.isfile(sa_output):
        os.remove(sa_output)
