# After changing this file, check it on:
#   http://lint.travis-ci.org/

language: python

os:
  - linux

python:
  - "3.7"

stages:
  - test

before_install:
  # Setup python environment
  - source devtools/travis_ci_before_install.sh
  - python -V
  # Set git info
  - git config --global user.name "Travis Deploy"
  - git config --global user.email "alongd@mit.edu"

cache: pip

jobs:
  include:
    - stage: test
      install:
        - echo $TRAVIS_OS_NAME
        - export PYTHONPATH=$PYTHONPATH:$(pwd)
        - echo "export PYTHONPATH=$PYTHONPATH:$(pwd)" >> ~/.bashrc
        - conda env create -f environment.yml
        - conda activate t3_env
        - make install-arc
        - make install-rms
      script:
        - coverage run -m pytest -ra -vv
        - coverage report
        - codecov

notifications:
    email: false
