# After changing this file, check it on:
#   http://lint.travis-ci.org/

language: python

os:
  - linux

python:
  - "3.7"

stages:
  - test

before_install:
  # Setup python environment
  - source devtools/travis_ci_before_install.sh
  - python -V
  # Set git info
  - git config --global user.name "Travis Deploy"
  - git config --global user.email "alongd@mit.edu"

cache: pip

jobs:
  include:
    - stage: test
      install:
        - echo $TRAVIS_OS_NAME
        - export PYTHONPATH=$PYTHONPATH:$(pwd)
        - echo 'export 'PYTHONPATH=$PYTHONPATH:$(pwd)'' >> ~/.bashrc
        - conda env create -f environment.yml
        - source activate t3_env
        - cd ..
        - git clone https://github.com/ReactionMechanismGenerator/ARC
        - cd ARC
        - export PYTHONPATH=$PYTHONPATH:$(pwd)
        - echo 'export 'PYTHONPATH=$PYTHONPATH:$(pwd)'' >> ~/.bashrc
        - cd ..
        - git clone https://github.com/ReactionMechanismGenerator/RMG-database
        - git clone https://github.com/ReactionMechanismGenerator/RMG-Py
        - cd RMG-Py
        - export PYTHONPATH=$PYTHONPATH:$(pwd)
        - echo 'export 'PYTHONPATH=$PYTHONPATH:$(pwd)'' >> ~/.bashrc
        - make
        - cd ../T3
        - . ~/.bashrc
        - conda remove --name t3_env --all -y
        - conda create -n t3_env python=3.7
        - source activate t3_env
        - make install-rms
      script:
        - coverage run -m pytest -ra -vv
        - coverage report
        - codecov

notifications:
    email: false
