codecov:
  token: 788d104c-5bc4-4986-8cfd-0d79930d97e1
  bot: "codecov-io"
  ci:
    - "travis.org"
  require_ci_to_pass: yes
coverage:
  range: 0..100
  round: nearest
  percision: 2
  ignore:
    - tests/**/*
comment:
  layout: "reach, diff, flags, files"
  require_changes: false
  branches: master
