coverage:
  ignore:
    - */tests/*
    - tandem/_version.py
  status:
    patch: false
    project:
      default:
        threshold: 50%
comment:
  layout: "header"
  require_changes: false
  branches: null
  behavior: once
