name: t3_env

channels:
  - conda-forge

dependencies:
  # ─── core ─────────────────────────────────────
  - python >=3.12
  - numpy >=2.1
  - pip

  # ─── conda-forge packages ─────────────────────
  - ase >=3.22.1
  - cairo
  - cairocffi
  - cmake
  - coverage
  - cython >=3.0
  - graphviz
  - ipython
  - jupyter
  - lpsolve55
  - mako
  - matplotlib
  - networkx
  - openbabel >=3
  - pandas
  - paramiko >=2.6.0
  - py3dmol >=0.8.0
  - pydantic
  - pydot
  - pytables
  - pytest
  - pytest-cov
  - pyyaml
  - rdkit >=2025.03
  - scipy
  - sphinx
  - sphinx_rtd_theme
  - sphinxcontrib-jsmath

  # ─── T3 specific packages (not in ARC) ─────────
  - cantera >=3.2.0
  - mkdocs-material >=5.1.7
  - mkdocs-material-extensions
