name: t3_env
channels:
  - defaults
  - rmg
  - rdkit
  - cantera
  - anaconda
  - pytorch
  - conda-forge
dependencies:
  - coverage
  - ipython
  - jupyter
  - matplotlib >=2.2.2
  - numpy >=1.15.4
  - paramiko >=2.6.0
  - pandas
  - py3dmol >= 0.8.0
  - pyparsing
  - pytest
  - python >=3.7
  - pyyaml
  - qcelemental
  - rdkit >=2019.09.2.0
  - rmg >=3.0.0
  - sphinx
