name: t3_env
channels:
  - defaults
  - rmg
  - conda-forge
dependencies:
  - conda-forge::ase >=3.15.0
  - conda-forge::cantera >=2.3.0
  - conda-forge::cclib >=1.7.0
  - coverage
  - conda-forge::julia
  - mako
  - mkdocs-material >=5.1.7
  - mkdocs-material-extensions
  - numpy >=1.10.0
  - anaconda::paramiko >=2.6.0
  - conda-forge::py3dmol >= 0.8.0
  - python >=3.7
  - pytest
  - pyyaml
  - conda-forge::qcelemental
  - rmg::rmg
  - sphinx
