name: t3_env
channels:
  - conda-forge
dependencies:
  - python=3.7
  - cantera=2.6
  - ca-certificates
  - openssl
  - ipython
  - pyyaml
  - rdkit >=2022.09.1
  - quantities >=0.13.0
  - certifi
  - rmg::pyrdl
  - scipy >=1.7.3
  - mkl
  - scikit-learn >=1.0.2
  - mpmath >=1.3.0
  - coolprop
  - rmg::pydqed
  - psutil
  - rmg::pydas
  - cclib >=1.7.2
  - openbabel >=3.1.1
  - lpsolve55
  - numdifftools >=0.9.41
  - qcelemental >=0.25.1
  - paramiko
  - py3dmol
  - numpy >=1.21.6
  - ase
  - xlwt
  - networkx
  - mako
  - pytest
  - rmg::symmetry
  - matplotlib
  - mkdocs-material >=5.1.7
  - mkdocs-material-extensions
  - mock
  - pyomo
