name: t3_env
channels:
  - defaults
  - rmg
  - anaconda
  - omnia
  - conda-forge
  - mjohnson541
dependencies:
  - cairo
  - cairocffi
  - rmg::cantera >=2.3.0
  - conda-forge::cclib >=1.7.0
  - rmg::chemprop
  - coolprop
  - coverage
  - cython >=0.25.2
  - ffmpeg
  - rmg::gprof2dot
  - graphviz
  - h5py
  - jinja2
  - jupyter
  - rmg::lpsolve55
  - markupsafe
  - matplotlib >=2.2.2
  - rmg::mopac
  - mpmath
  - rmg::muq2
  - networkx
  - rmg::numdifftools
  - numpy >=1.15.4
  - conda-forge::openbabel >= 3
  - pandas
  - psutil
  - rmg::pydas >=1.0.2
  - pydot
  - rmg::pydqed >=1.0.1
  - pymongo
  - pyparsing
  - rmg::pyrdl
  - python >=3.7
  - pyyaml
  - rmg::quantities
  - rmg::rdkit >=2020.03.3.0
  - scikit-learn
  - scipy
  - rmg::symmetry
  - xlrd
  - xlwt
  - anaconda::sphinx_rtd_theme
  - anaconda::paramiko >=2.6.0
  - conda-forge::py3dmol >= 0.8.0
  - conda-forge::ase >=3.15.0
  - anaconda::ipython
  - anaconda::sphinx
  - conda-forge::qcelemental
  - mako
  - pytables
  - pytorch::pytorch >=1.12.0
  - anaconda::pytest
  - conda-forge::torchani
  - conda-forge::xtb
  - mkdocs-material >=5.1.7
  - mkdocs-material-extensions
  - mock
  - pyomo
