name: t3_env
channels:
  - defaults
  - rmg
  - anaconda
  - omnia
  - conda-forge
  - mjohnson541
  - psi4
dependencies:
  - ase >=3.15.0
  - cairo
  - cairocffi
  - rmg::cantera >=2.3.0
  - cclib >=1.6
  - rmg::chemprop
  - codecov
  - coolprop
  - coverage
  - cython >=0.25.2
  - ffmpeg
  - rmg::gprof2dot
  - graphviz
  - h5py
  - ipython
  - jinja2
  - jupyter
  - rmg::lpsolve55
  - mako
  - markupsafe
  - matplotlib >=2.2.2
  - mkdocs-material >=5.1.7
  - mkdocs-material-extensions
  - mock
  - rmg::mopac
  - mpmath
  - networkx
  - nose
  - rmg::numdifftools
  - numpy >=1.15.4
  - openbabel
  - paramiko >=2.6.0
  - pandas
  - psi4
  - psutil
  - py3dmol >= 0.8.0
  - rmg::pydas >=1.0.2
  - pydot
  - rmg::pydqed >=1.0.1
  - pymongo
  - pyparsing
  - rmg::pyrdl
  - pyrms
  - python >=3.7
  - pytest
  - pyyaml
  - qcelemental
  - rmg::quantities
  - rmg::rdkit >=2020.03.3.0
  - scikit-learn
  - scipy
  - sphinx
  - rmg::symmetry
  - xlwt
