#!/usr/bin/env python
# -*- coding: utf-8 -*-

title = 'Arkane kinetics calculation'
description = """
Generated by ARC.
"""

modelChemistry = LevelOfTheory(method='wb97xd2023',basis='def2tzvp',software='gaussian')

frequencyScaleFactor = 0.988
useHinderedRotors = True
useAtomCorrections = True
useBondCorrections = False

species('Kor_R', '/path/to/arc_project/calcs/statmech/kinetics/species/Kor_R.py',
        structure=SMILES('CC(CC=O)OO'), spinMultiplicity=1)
species('RAdd_R', '/path/to/arc_project/calcs/statmech/kinetics/species/RAdd_R.py',
        structure=SMILES('[CH2]C1CC=CC1=C'), spinMultiplicity=2)
species('Kor_P', '/path/to/arc_project/calcs/statmech/kinetics/species/Kor_P.py',
        structure=SMILES('CC1CC(O)OO1'), spinMultiplicity=1)
species('RAdd_P', '/path/to/arc_project/calcs/statmech/kinetics/species/RAdd_P.py',
        structure=SMILES('[CH2]C12C=CCC1C2'), spinMultiplicity=2)

transitionState('TS0', '/path/to/arc_project/calcs/statmech/kinetics/TSs/TS0.py')
transitionState('TS1', '/path/to/arc_project/calcs/statmech/kinetics/TSs/TS1.py')

reaction(
    label='Kor_R <=> Kor_P',
    reactants=['Kor_R'],
    products=['Kor_P'],
    transitionState='TS0',
    tunneling='Eckart',
)
reaction(
    label='RAdd_R <=> RAdd_P',
    reactants=['RAdd_R'],
    products=['RAdd_P'],
    transitionState='TS1',
    tunneling='Eckart',
)

kinetics(label='Kor_R <=> Kor_P',
         Tmin=(300, 'K'), Tmax=(3000, 'K'), Tcount=50)
kinetics(label='RAdd_R <=> RAdd_P',
         Tmin=(300, 'K'), Tmax=(3000, 'K'), Tcount=50)


