# check that Python and Julia are being accessed from the t3_env
echo checking which python...
which python
echo checking which julia...
which julia

echo linking python-jl to python...
ln -sfn $(which python-jl) $(which python)

echo installing PyCall...
julia devtools/install_pycall.jl

echo installing pyrms, RMS, and all required Julia packages...
python -c "import pyrms; pyrms.install()"
