#!/usr/bin/env python
# -*- coding: utf-8 -*-

title = 'Arkane kinetics calculation'
description = """
Generated by ARC.
"""


frequencyScaleFactor = 1.0
useHinderedRotors = True
useAtomCorrections = False
useBondCorrections = False

species('OH', '/path/to/arc_project/calcs/Species/OH/freq_a2354/OH.yml',
        structure=SMILES('[OH]'), spinMultiplicity=2)
species('H2O', '/path/to/arc_project/calcs/Species/H2O/freq_a2353/H2O.yml',
        structure=SMILES('O'), spinMultiplicity=1)
species('CH3', '/path/to/arc_project/calcs/Species/CH3/freq_a2351/CH3.yml',
        structure=SMILES('[CH3]'), spinMultiplicity=2)
species('CH4', '/path/to/arc_project/calcs/Species/CH4/freq_a2352/CH4.yml',
        structure=SMILES('C'), spinMultiplicity=1)

transitionState('TS0', '/path/to/arc_project/calcs/TSs/TS0/freq_a2355/TS0.yml')

reaction(
    label='CH4 + OH <=> CH3 + H2O',
    reactants=['CH4', 'OH'],
    products=['CH3', 'H2O'],
    transitionState='TS0',
    tunneling='Eckart',
)

kinetics(label='CH4 + OH <=> CH3 + H2O',
         Tmin=(300, 'K'), Tmax=(3000, 'K'), Tcount=50)


