#!/usr/bin/env python
# -*- coding: utf-8 -*-

title = 'Arkane thermo calculation'
description = """
Generated by ARC.
"""

modelChemistry = LevelOfTheory(method='wb97xd2023',basis='def2tzvp',software='gaussian')

frequencyScaleFactor = 0.988
useHinderedRotors = True
useAtomCorrections = True
useBondCorrections = True
bondCorrectionType = 'p'

species('Kor_R', '/path/to/arc_project/calcs/statmech/thermo/species/Kor_R.py',
        structure=SMILES('CC(CC=O)OO'), spinMultiplicity=1)
species('Kor_P', '/path/to/arc_project/calcs/statmech/thermo/species/Kor_P.py',
        structure=SMILES('CC1CC(O)OO1'), spinMultiplicity=1)
species('RAdd_R', '/path/to/arc_project/calcs/statmech/thermo/species/RAdd_R.py',
        structure=SMILES('[CH2]C1CC=CC1=C'), spinMultiplicity=2)
species('RAdd_P', '/path/to/arc_project/calcs/statmech/thermo/species/RAdd_P.py',
        structure=SMILES('[CH2]C12C=CCC1C2'), spinMultiplicity=2)
species('CH3', '/path/to/arc_project/calcs/statmech/thermo/species/CH3.py',
        structure=SMILES('[CH3]'), spinMultiplicity=2)
species('CS', '/path/to/arc_project/calcs/statmech/thermo/species/CS.py',
        structure=SMILES('[C-]#[S+]'), spinMultiplicity=1)
species('CCS', '/path/to/arc_project/calcs/statmech/thermo/species/CCS.py',
        structure=SMILES('C[C]=S'), spinMultiplicity=2)
species('HOO_R', '/path/to/arc_project/calcs/statmech/thermo/species/HOO_R.py',
        structure=SMILES('CC(O)O[O]'), spinMultiplicity=2)
species('CH3CHO', '/path/to/arc_project/calcs/statmech/thermo/species/CH3CHO.py',
        structure=SMILES('CC=O'), spinMultiplicity=1)
species('HO2', '/path/to/arc_project/calcs/statmech/thermo/species/HO2.py',
        structure=SMILES('[O]O'), spinMultiplicity=2)
species('Sub_R', '/path/to/arc_project/calcs/statmech/thermo/species/Sub_R.py',
        structure=SMILES('[CH2]CCC(=O)CSC'), spinMultiplicity=2)
species('C5one', '/path/to/arc_project/calcs/statmech/thermo/species/C5one.py',
        structure=SMILES('O=C1CCCC1'), spinMultiplicity=1)
species('SCH3', '/path/to/arc_project/calcs/statmech/thermo/species/SCH3.py',
        structure=SMILES('C[S]'), spinMultiplicity=2)




thermo('Kor_R', 'NASA')
thermo('Kor_P', 'NASA')
thermo('RAdd_R', 'NASA')
thermo('RAdd_P', 'NASA')
thermo('CH3', 'NASA')
thermo('CS', 'NASA')
thermo('CCS', 'NASA')
thermo('HOO_R', 'NASA')
thermo('CH3CHO', 'NASA')
thermo('HO2', 'NASA')
thermo('Sub_R', 'NASA')
thermo('C5one', 'NASA')
thermo('SCH3', 'NASA')

