#!/usr/bin/env python
# -*- coding: utf-8 -*-

title = 'Arkane thermo calculation'
description = """
Generated by ARC.
"""

modelChemistry = CompositeLevelOfTheory(
    freq=LevelOfTheory(method='wb97xd',basis='def2tzvp',software='gaussian'),
    energy=LevelOfTheory(method='dlpnoccsd(t)f122023',basis='ccpvtzf12',software='orca')
)

useHinderedRotors = True
useAtomCorrections = True
useBondCorrections = True
bondCorrectionType = 'p'

species('benzyl', '/path/to/arc_project/calcs/statmech/thermo/species/benzyl.py',
        structure=SMILES('[CH2]C1=CC=CC=C1'), spinMultiplicity=2)




thermo('benzyl', 'NASA')

