name: continuous integration

on:
  push:
  pull_request:
    branches:
      - master
    types: [opened, synchronize, reopened, ready_for_review, review_requested]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up miniconda Python 3.7
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: t3_env
        environment-file: environment.yml
        python-version: 3.7
        auto-activate-base: false

    - name: Install codecov
      run: conda install -y -c conda-forge codecov

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        conda activate t3_env
        make install
        echo $(pwd)
        conda list

    - name: Test with PyTest
      shell: bash -l {0}
      run: |
        cd ..
        cd RMG-Py
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        cd ..
        cd ARC
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        cd ..
        cd T3
        conda activate t3_env
        make test
        codecov
