name: CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, ready_for_review, review_requested]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
    - uses: actions/checkout@v2

    - name: Setup Mambaforge Python 3.7
      uses: conda-incubator/setup-miniconda@v2
      with:
        environment-file: environment.yml
        miniforge-variant: Mambaforge
        miniforge-version: latest
        activate-environment: t3_env
        python-version: 3.7
        use-mamba: true

    - name: Update environment
      run: |
        mamba env update -n t3_env -f environment.yml
        conda list

    - name: Install codecov
      run: |
        mamba install -y -c conda-forge codecov
        mamba install -y pytest-cov

    - name: Install dependencies
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        echo 'export PYTHONPATH=$PYTHONPATH:'"$(pwd)" >> ~/.bashrc
        make install

    - name: Test
      shell: bash -l {0}
      run: |
        source ~/.bashrc
        echo $PYTHONPATH
        conda activate t3_env
        make test
        codecov --token=788d104c-5bc4-4986-8cfd-0d79930d97e1

    - name: Code coverage
      run: codecov
