name: Docker Image Build and Push

on:
  push:
    branches:
        - main
  pull_request:
    branches:
        - main
    paths:
        - 'devtools/Dockerfile'
jobs:
  ci-check:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Add steps for CI checks of the Dockerfile
      - name: Build RMG-Py
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./devtools/Dockerfile_rmgpy
          push: false
      - name: Build T3
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./devtools/Dockerfile
          push: false
  
  build-and-push:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Build and push RMG-Py
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./devtools/Dockerfile_rmgpy
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/rmgpy:latest
    - name: Build and push T3
      uses: docker/build-push-action@v2
      with:
        context: .
        file: ./devtools/Dockerfile
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/thetandemtool-t3:latest
        