name: Docker Image Build and Push (Debug)

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
    types: [opened, synchronize, reopened, ready_for_review, review_requested]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      
      - name: Debug
        run: |
          echo "Debugging the GitHub Action"
          echo "Current directory: $(pwd)"
          echo "Files in current directory: $(ls)"
          echo "Dockerfile: $(cat ./devtools/Dockerfile)"
          echo "Dockerfile: ${{ secrets.DOCKERHUB_USERNAME}}"
          echo "Dockerfile: ${{ secrets.DOCKERHUB_TOKEN}}"
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./devtools/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/thetandemtool-t3:latest


